version: "3.1"

services:
  app:
    build: ./app
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      DICT_CH_ID: ${DICT_CH_ID}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}