version: "3.1"

services:
  app:
    build: ./app
    tty: true
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
    volumes:
      - ./app:/root/src
