version: "3.1"

services:
  app:
    build: "./app"
    tty: true
    restart: always
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
