name: Build Container

defaults:
  run:
    working-directory: ./app

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: set tag
        run: |-
          export TIMESTAMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTAMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/102ch/discord-tts-bot:${{ env.IMAGE_TAG }},ghcr.io/102ch/discord-tts-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
