name: Build Container

defaults:
  run:
    working-directory: ./app

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            arch: amd64
          - runner: arm64
            arch: arm64
    runs-on: ${{ matrix.platform.runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: set tag
        run: |-
          export TIMESTAMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTAMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/${{ matrix.platform.arch }}
          push: true
          tags: ghcr.io/102ch/discord-tts-bot:${{ env.IMAGE_TAG }}-${{ matrix.platform.arch }},ghcr.io/102ch/discord-tts-bot:latest-${{ matrix.platform.arch }}
          cache-from: type=gha,scope=${{ matrix.platform.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform.arch }}

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: set tag
        run: |-
          export TIMESTAMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTAMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/102ch/discord-tts-bot:${{ env.IMAGE_TAG }} \
            -t ghcr.io/102ch/discord-tts-bot:latest \
            ghcr.io/102ch/discord-tts-bot:${{ env.IMAGE_TAG }}-amd64 \
            ghcr.io/102ch/discord-tts-bot:${{ env.IMAGE_TAG }}-arm64
