name: Build Container

defaults:
  run:
    working-directory: ./app

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/102ch/discord-tts-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy to Server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'root@mc.k1h.dev:5000'
          privateKey: ${{ secrets.SSH_PRIVATEKEY }}
          command: cd discord-tts-bot; git pull; docker pull ghcr.io/102ch/discord-tts-bot:latest; docker-compose -f docker-compose-release.yml up -d
